### ISSUE TITLE
提问前, 请自查

### ISSUE THREAD

**Issue by floydawong** [Sublime-Chinese/sublime-zh#1]
## 资料
- Github: https://github.com/Sublime-Chinese 
- 简书: http://www.jianshu.com/collection/1627f31c077b 
## 提问链接

https://github.com/Sublime-Chinese/sublime-zh/issues
## 提问前, 请自查:
1. 是否是官网下载的Sublime? 
2. Console控制台(Ctrl + `)是否有报错? 
3. 百度是否有答案? 
4. Google是否有答案?

**Comment by lifesign** [comment]
这个不太适合放在 issue 中，放在 readme 中引导更佳
